version: "3.1"

networks:
  local-cat:

services:
  consul:
    image: bitnami/consul:latest
    container_name: consul-cat
    networks:
      - local-cat
    ports:
      - "8500:8500"
      - "8600:8600"
  db:
    image: mongo:3
    container_name: mongo-cat
    networks:
      - local-cat
    ports:
      - "27017:27017"
    restart: always
  typesofcat:
    image: typesofcat:latest
    container_name: typesofcat
    depends_on:
      - db
      - consul
    environment:
      TZ: America/Sao_Paulo
    links:
      - db
      - consul
    networks:
      - local-cat
    ports:
      - "8081:8080"
    restart: always
  thecat:
    image: thecat:latest
    container_name: thecat
    depends_on:
      - db
      - consul
    environment:
      TZ: America/Sao_Paulo
    links:
      - db
      - consul
    networks:
      - local-cat
    ports:
      - "8080:8080"
    command:
      - gradle build
    restart: always


